In [1]:
import numpy as np
import statistics as st
import pandas as pd

In [2]:
df = pd.read_excel('Tabla.xlsx')
df.head()

Rendimiento S&P
0         0.006378
1         0.004021
2         0.007009
3         0.001661
4         0.001302

In [3]:
df.tail()

Rendimiento S&P
591         0.000133
592        -0.020713
593        -0.017617
594         0.011459
595         0.003919

In [4]:
df.shape

(596, 1)

Segundo día

In [5]:
#2
#596 días
rend2_1 = df['Rendimiento S&P']
rend2_1 = np.array(rend2_1)
rend2_1

array([ 6.37843324e-03,  4.02054262e-03,  7.00914585e-03,  1.66096392e-03,
        1.30208347e-03, -1.11284596e-03,  7.00902609e-03,  6.72692617e-03,
       -3.53071313e-03,  9.37100631e-03, -1.61769775e-03,  4.37564815e-03,
        8.03436443e-03,  2.17200493e-03, -5.60132635e-04,  6.02439421e-04,
        1.17716380e-02, -6.75473632e-03, -1.09586426e-02,  4.88865875e-04,
       -6.48298662e-04, -2.14366803e-02, -4.18425412e-02,  1.72905737e-02,
       -5.01413842e-03, -3.82590522e-02,  1.48256453e-02,  1.38186656e-02,
        2.60952183e-03,  1.33134400e-02,  1.19968616e-02,  3.73399822e-04,
       -5.85851713e-03, -5.51166462e-03,  9.73077555e-04,  1.59012783e-02,
        1.16884387e-02, -1.27883117e-02, -1.11578060e-02, -1.34139658e-02,
        5.05878544e-03,  1.09716175e-02,  2.63538301e-03, -4.83991694e-04,
        4.45314825e-03,  1.72295465e-02, -1.27479704e-03, -6.38391044e-03,
       -5.74097014e-03, -7.82236274e-04,  1.70199808e-03, -1.43060406e-02,
        1.48070847e-03, -

In [6]:
st.mean([rend2_1[0], rend2_1[1]])

0.005199487931262691

In [7]:
st.mean([rend2_1[594], rend2_1[595]])

0.007688796473887964

In [8]:
rend2 = []
for i in range(298):
    rend2.append(st.mean([rend2_1[2*i], rend2_1[(2*i) + 1]]))
rend2

[0.005199487931262691,
 0.004335054882334826,
 9.46187562335391e-05,
 0.00686797612721082,
 0.0029201465869874146,
 0.001378975202859351,
 0.005103184677658969,
 2.1153392779793166e-05,
 0.002508450858591677,
 -0.005234888349369363,
 -0.011042489472352821,
 -0.01227598375039752,
 -0.021636595313042968,
 0.014322155438855325,
 0.00796148092932708,
 0.006185130732937193,
 -0.005685090872539371,
 0.00843717791976694,
 -0.0005499364957905596,
 -0.01228588589183532,
 0.008015201449868867,
 0.001075695659308573,
 0.010841347379046847,
 -0.003829353738218508,
 -0.0032616032083466716,
 -0.0063020212512835665,
 -0.00018249168873497195,
 -0.023337347163284144,
 0.004683877449196678,
 0.005377429297574199,
 -0.005027360511247865,
 0.00916976192745649,
 -0.009416536086201004,
 0.005523956555976572,
 0.0026630495447049754,
 0.009340704253303094,
 -0.0024557807372694463,
 -0.00425847358509776,
 -0.005817756940241879,
 0.005746574774006516,
 -0.002837695136093458,
 -0.004744084514728911,
 0.008090895

In [9]:
rend2 = pd.DataFrame({'Medias de Rendimientos': rend2})
rend2.to_excel('Rend2.xlsx')

In [10]:
rend2

Medias de Rendimientos
0                  0.005199
1                  0.004335
2                  0.000095
3                  0.006868
4                  0.002920
..                      ...
293                0.006620
294                0.002218
295                0.008432
296               -0.019165
297                0.007689

[298 rows x 1 columns]

Tercer día

In [11]:
df

Rendimiento S&P
0           0.006378
1           0.004021
2           0.007009
3           0.001661
4           0.001302
..               ...
591         0.000133
592        -0.020713
593        -0.017617
594         0.011459
595         0.003919

[596 rows x 1 columns]

In [12]:
#3
#594 días
#ELiminamos 2 observaciones
rend3_1 = df['Rendimiento S&P'][2:596:1]
rend3_1 = np.array(rend3_1)
rend3_1

array([ 7.00914585e-03,  1.66096392e-03,  1.30208347e-03, -1.11284596e-03,
        7.00902609e-03,  6.72692617e-03, -3.53071313e-03,  9.37100631e-03,
       -1.61769775e-03,  4.37564815e-03,  8.03436443e-03,  2.17200493e-03,
       -5.60132635e-04,  6.02439421e-04,  1.17716380e-02, -6.75473632e-03,
       -1.09586426e-02,  4.88865875e-04, -6.48298662e-04, -2.14366803e-02,
       -4.18425412e-02,  1.72905737e-02, -5.01413842e-03, -3.82590522e-02,
        1.48256453e-02,  1.38186656e-02,  2.60952183e-03,  1.33134400e-02,
        1.19968616e-02,  3.73399822e-04, -5.85851713e-03, -5.51166462e-03,
        9.73077555e-04,  1.59012783e-02,  1.16884387e-02, -1.27883117e-02,
       -1.11578060e-02, -1.34139658e-02,  5.05878544e-03,  1.09716175e-02,
        2.63538301e-03, -4.83991694e-04,  4.45314825e-03,  1.72295465e-02,
       -1.27479704e-03, -6.38391044e-03, -5.74097014e-03, -7.82236274e-04,
        1.70199808e-03, -1.43060406e-02,  1.48070847e-03, -1.84569184e-03,
       -2.54848873e-02, -

In [13]:
st.mean([rend3_1[0], rend3_1[1], rend3_1[2]])

0.0033240644121683522

In [14]:
st.mean([rend3_1[591], rend3_1[592], rend3_1[593]])

-0.0007464678703919207

In [15]:
rend3 = []
for i in range(198):
    rend3.append(st.mean([rend3_1[3*i], rend3_1[(3*i) + 1], rend3_1[(3*i) +2]]))
rend3

[0.0033240644121683522,
 0.004207702098351104,
 0.0014075318084810031,
 0.0048606725031894865,
 0.00393798160879269,
 -0.0057415043407912855,
 -0.0213091733681109,
 -0.008660872322417973,
 0.010417944235143728,
 0.008561233832269338,
 -0.003465701396704368,
 0.004933801764329041,
 -0.006504328781718157,
 0.004374336259946238,
 0.0068026325724980415,
 -0.00430237228417693,
 -0.0037077780121495935,
 -0.016173462056718862,
 0.0021489453568992525,
 0.0012070188001160886,
 -0.0012748477097465998,
 0.0047929693079013045,
 0.00446747862237095,
 0.0018978367514547977,
 -0.007329278333021573,
 0.004442841165466158,
 -0.004302447163634726,
 0.004641857673663448,
 0.006232327574951195,
 -0.0014254720647724093,
 0.00018681199239023279,
 0.002487353676554263,
 -0.005338946219224514,
 0.005501113968667732,
 0.004567613999265755,
 0.0011582407229049547,
 5.8704391854660325e-05,
 -0.0023925097746494792,
 -0.0009316117785014146,
 -0.006753052924607348,
 0.0033270188981030387,
 0.004023248304148677,
 0.

In [16]:
rend3 = pd.DataFrame({'Medias de Rendimientos': rend3})
rend3.to_excel('Rend3.xlsx')

In [17]:
rend3

Medias de Rendimientos
0                  0.003324
1                  0.004208
2                  0.001408
3                  0.004861
4                  0.003938
..                      ...
193                0.011862
194               -0.011158
195                0.004478
196               -0.001283
197               -0.000746

[198 rows x 1 columns]

Cuarto día

In [18]:
df

Rendimiento S&P
0           0.006378
1           0.004021
2           0.007009
3           0.001661
4           0.001302
..               ...
591         0.000133
592        -0.020713
593        -0.017617
594         0.011459
595         0.003919

[596 rows x 1 columns]

In [19]:
#4
#596 días
rend4_1 = df['Rendimiento S&P']
rend4_1 = np.array(rend4_1)
rend4_1

array([ 6.37843324e-03,  4.02054262e-03,  7.00914585e-03,  1.66096392e-03,
        1.30208347e-03, -1.11284596e-03,  7.00902609e-03,  6.72692617e-03,
       -3.53071313e-03,  9.37100631e-03, -1.61769775e-03,  4.37564815e-03,
        8.03436443e-03,  2.17200493e-03, -5.60132635e-04,  6.02439421e-04,
        1.17716380e-02, -6.75473632e-03, -1.09586426e-02,  4.88865875e-04,
       -6.48298662e-04, -2.14366803e-02, -4.18425412e-02,  1.72905737e-02,
       -5.01413842e-03, -3.82590522e-02,  1.48256453e-02,  1.38186656e-02,
        2.60952183e-03,  1.33134400e-02,  1.19968616e-02,  3.73399822e-04,
       -5.85851713e-03, -5.51166462e-03,  9.73077555e-04,  1.59012783e-02,
        1.16884387e-02, -1.27883117e-02, -1.11578060e-02, -1.34139658e-02,
        5.05878544e-03,  1.09716175e-02,  2.63538301e-03, -4.83991694e-04,
        4.45314825e-03,  1.72295465e-02, -1.27479704e-03, -6.38391044e-03,
       -5.74097014e-03, -7.82236274e-04,  1.70199808e-03, -1.43060406e-02,
        1.48070847e-03, -

In [20]:
st.mean([rend4_1[0], rend4_1[1], rend4_1[2], rend4_1[3]])

0.004767271406798759

In [21]:
st.mean([rend4_1[592], rend4_1[593], rend4_1[594], rend4_1[595]])

-0.00573819232747721

In [22]:
rend4 = []
for i in range(149):
    rend4.append(st.mean([rend4_1[4*i], rend4_1[(4*i)+1], rend4_1[(4*i)+2], rend4_1[(4*i)+3]]))
rend4

[0.004767271406798759,
 0.003481297441722179,
 0.002149560894923383,
 0.0025621690352193812,
 -0.0013632187453888431,
 -0.011659236611375171,
 -0.0036572199370938224,
 0.007073305831132136,
 0.0013760435236137842,
 -0.00641791119381294,
 0.00454544855458872,
 0.0035059968204141693,
 -0.004781812229815119,
 -0.011759919426009558,
 0.005030653373385438,
 0.0020712007081043126,
 -0.0019462897651122166,
 0.006001876899004034,
 -0.003357127161183603,
 -3.559108311768143e-05,
 -0.003790889825411185,
 0.00638794051538578,
 0.0012626488251810365,
 0.001980010125358277,
 -0.0010707023823938286,
 0.0012179423208263371,
 0.0032470995460349866,
 0.00047419469680423773,
 -0.0011772572383073067,
 -0.004153639625900401,
 0.0001195900405986044,
 0.003783251459659011,
 0.0034607613550751396,
 0.0015434993229082854,
 0.00042403913841848655,
 -0.0015827728485984342,
 0.003344931449414632,
 0.001161763790530971,
 -0.0031039071292273254,
 0.0039243239682537736,
 0.0029324805637191967,
 0.000412195302955012

In [23]:
rend4 = pd.DataFrame({'Medias de Rendimientos': rend4})
rend4

Medias de Rendimientos
0                  0.004767
1                  0.003481
2                  0.002150
3                  0.002562
4                 -0.001363
..                      ...
144               -0.006767
145                0.012352
146               -0.006119
147                0.005325
148               -0.005738

[149 rows x 1 columns]

In [24]:
rend4.to_excel('Rend4.xlsx')

Quinto día

In [25]:
df

Rendimiento S&P
0           0.006378
1           0.004021
2           0.007009
3           0.001661
4           0.001302
..               ...
591         0.000133
592        -0.020713
593        -0.017617
594         0.011459
595         0.003919

[596 rows x 1 columns]

In [26]:
#5
#595 días
#Eliminamos 1 observacion
rend5_1 = df['Rendimiento S&P'][1:596:1]
rend5_1 = np.array(rend5_1)
rend5_1

array([ 4.02054262e-03,  7.00914585e-03,  1.66096392e-03,  1.30208347e-03,
       -1.11284596e-03,  7.00902609e-03,  6.72692617e-03, -3.53071313e-03,
        9.37100631e-03, -1.61769775e-03,  4.37564815e-03,  8.03436443e-03,
        2.17200493e-03, -5.60132635e-04,  6.02439421e-04,  1.17716380e-02,
       -6.75473632e-03, -1.09586426e-02,  4.88865875e-04, -6.48298662e-04,
       -2.14366803e-02, -4.18425412e-02,  1.72905737e-02, -5.01413842e-03,
       -3.82590522e-02,  1.48256453e-02,  1.38186656e-02,  2.60952183e-03,
        1.33134400e-02,  1.19968616e-02,  3.73399822e-04, -5.85851713e-03,
       -5.51166462e-03,  9.73077555e-04,  1.59012783e-02,  1.16884387e-02,
       -1.27883117e-02, -1.11578060e-02, -1.34139658e-02,  5.05878544e-03,
        1.09716175e-02,  2.63538301e-03, -4.83991694e-04,  4.45314825e-03,
        1.72295465e-02, -1.27479704e-03, -6.38391044e-03, -5.74097014e-03,
       -7.82236274e-04,  1.70199808e-03, -1.43060406e-02,  1.48070847e-03,
       -1.84569184e-03, -

In [27]:
st.mean([rend5_1[0], rend5_1[1], rend5_1[2], rend5_1[3], rend5_1[4]])

0.002575977979336813

In [28]:
st.mean([rend5_1[115], rend5_1[116], rend5_1[117], rend5_1[118]])

-0.004153639625900401

In [29]:
rend5 = []
for i in range(119):
    rend5.append(st.mean([rend5_1[5*i], rend5_1[(5*i)+1], rend5_1[(5*i)+2], rend5_1[(5*i)+3], rend5_1[(5*i)+4]]))
rend5

[0.002575977979336813,
 0.00359170953597293,
 0.0029248648590256094,
 -0.0012202347287102702,
 -0.017852367681918127,
 0.011312826876146044,
 0.0011755147831928217,
 -0.004122571867347119,
 0.006961140707586481,
 -0.002495983163047001,
 -0.012269143656900143,
 -0.0004936137412666401,
 0.002408482571978039,
 0.004890069795813199,
 -0.0005646873831662252,
 -0.0016727113551040064,
 0.0018478847946270943,
 0.004257244341318751,
 0.00021087706507514178,
 -0.0031828764304546327,
 0.004335056641004712,
 0.0027494980539085685,
 -0.001748656710087107,
 -0.002882481543290067,
 -0.0007240317785207973,
 0.0044322856275850865,
 0.00297699773609829,
 0.0021513183239311446,
 -0.002311916516250327,
 0.0031275103482717066,
 -0.0027716686355218605,
 0.0030598129342730867,
 0.003616527612499708,
 -0.002485489876549923,
 0.0018076113165408278,
 0.0018214615743198665,
 -0.0011463310393575023,
 -0.0008521831083807118,
 -0.01231227761311973,
 0.002940479255094303,
 -0.00461883286409672,
 0.002556070870837476

In [30]:
rend5 = pd.DataFrame({'Medias de Rendimientos': rend5})
rend5

Medias de Rendimientos
0                  0.002576
1                  0.003592
2                  0.002925
3                 -0.001220
4                 -0.017852
..                      ...
114                0.005985
115               -0.002649
116               -0.000426
117                0.006881
118               -0.004564

[119 rows x 1 columns]

In [31]:
rend5.to_excel('Rend5.xlsx')

Sexto día

In [32]:
df

Rendimiento S&P
0           0.006378
1           0.004021
2           0.007009
3           0.001661
4           0.001302
..               ...
591         0.000133
592        -0.020713
593        -0.017617
594         0.011459
595         0.003919

[596 rows x 1 columns]

In [33]:
#6
#594 días
#Eliminamos 2 observaciones
rend6_1 = df['Rendimiento S&P'][2:596:1]
rend6_1 = np.array(rend6_1)
rend6_1

array([ 7.00914585e-03,  1.66096392e-03,  1.30208347e-03, -1.11284596e-03,
        7.00902609e-03,  6.72692617e-03, -3.53071313e-03,  9.37100631e-03,
       -1.61769775e-03,  4.37564815e-03,  8.03436443e-03,  2.17200493e-03,
       -5.60132635e-04,  6.02439421e-04,  1.17716380e-02, -6.75473632e-03,
       -1.09586426e-02,  4.88865875e-04, -6.48298662e-04, -2.14366803e-02,
       -4.18425412e-02,  1.72905737e-02, -5.01413842e-03, -3.82590522e-02,
        1.48256453e-02,  1.38186656e-02,  2.60952183e-03,  1.33134400e-02,
        1.19968616e-02,  3.73399822e-04, -5.85851713e-03, -5.51166462e-03,
        9.73077555e-04,  1.59012783e-02,  1.16884387e-02, -1.27883117e-02,
       -1.11578060e-02, -1.34139658e-02,  5.05878544e-03,  1.09716175e-02,
        2.63538301e-03, -4.83991694e-04,  4.45314825e-03,  1.72295465e-02,
       -1.27479704e-03, -6.38391044e-03, -5.74097014e-03, -7.82236274e-04,
        1.70199808e-03, -1.43060406e-02,  1.48070847e-03, -1.84569184e-03,
       -2.54848873e-02, -

In [34]:
st.mean([rend6_1[0], rend6_1[1], rend6_1[2], rend6_1[3], rend6_1[4], rend6_1[5]])

0.003765883255259728

In [35]:
st.mean([rend6_1[588], rend6_1[589], rend6_1[590], rend6_1[591], rend6_1[592], rend6_1[593]])

-0.0010148174792556505

In [36]:
rend6 = []
for i in range(99):
    rend6.append(st.mean([rend6_1[6*i], rend6_1[(6*i)+1], rend6_1[(6*i)+2], rend6_1[(6*i)+3], rend6_1[(6*i)+4], rend6_1[(6*i)+5]]))

rend6 = pd.DataFrame({'Medias de Rendimientos': rend6})
rend6.to_excel('Rend6.xlsx')

In [37]:
rend6

Medias de Rendimientos
0                 0.003766
1                 0.003134
2                -0.000902
3                -0.014985
4                 0.009490
..                     ...
94                0.014805
95               -0.001520
96                0.011924
97               -0.003340
98               -0.001015

[99 rows x 1 columns]

Séptimo día

In [38]:
df

Rendimiento S&P
0           0.006378
1           0.004021
2           0.007009
3           0.001661
4           0.001302
..               ...
591         0.000133
592        -0.020713
593        -0.017617
594         0.011459
595         0.003919

[596 rows x 1 columns]

In [39]:
#7
#Nos quedamos con 595 días
#Se elimina 1 observacion 
rend7_1 = df['Rendimiento S&P'][1:596:1]
rend7_1 = np.array(rend7_1)
rend7_1

array([ 4.02054262e-03,  7.00914585e-03,  1.66096392e-03,  1.30208347e-03,
       -1.11284596e-03,  7.00902609e-03,  6.72692617e-03, -3.53071313e-03,
        9.37100631e-03, -1.61769775e-03,  4.37564815e-03,  8.03436443e-03,
        2.17200493e-03, -5.60132635e-04,  6.02439421e-04,  1.17716380e-02,
       -6.75473632e-03, -1.09586426e-02,  4.88865875e-04, -6.48298662e-04,
       -2.14366803e-02, -4.18425412e-02,  1.72905737e-02, -5.01413842e-03,
       -3.82590522e-02,  1.48256453e-02,  1.38186656e-02,  2.60952183e-03,
        1.33134400e-02,  1.19968616e-02,  3.73399822e-04, -5.85851713e-03,
       -5.51166462e-03,  9.73077555e-04,  1.59012783e-02,  1.16884387e-02,
       -1.27883117e-02, -1.11578060e-02, -1.34139658e-02,  5.05878544e-03,
        1.09716175e-02,  2.63538301e-03, -4.83991694e-04,  4.45314825e-03,
        1.72295465e-02, -1.27479704e-03, -6.38391044e-03, -5.74097014e-03,
       -7.82236274e-04,  1.70199808e-03, -1.43060406e-02,  1.48070847e-03,
       -1.84569184e-03, -

In [40]:
st.mean([rend7_1[0], rend7_1[1], rend7_1[2], rend7_1[3], rend7_1[4], rend7_1[5], rend7_1[6]])

0.003802263164443672

In [41]:
st.mean([rend7_1[588], rend7_1[589], rend7_1[590], rend7_1[591], rend7_1[592], rend7_1[593], rend7_1[594]])

0.0007642929563531707

In [42]:
rend7 = []
for i in range(85):
    rend7.append(st.mean([rend7_1[7*i], rend7_1[(7*i)+1], rend7_1[(7*i)+2], rend7_1[(7*i)+3], rend7_1[(7*i)+4], rend7_1[(7*i)+5], rend7_1[(7*i)+6]]))

rend7 = pd.DataFrame({'Medias de Rendimientos': rend7})
rend7.to_excel('Rend7.xlsx')

In [43]:
rend7

Medias de Rendimientos
0                 0.003802
1                 0.002606
2                -0.003848
3                -0.005224
4                 0.004455
..                     ...
80                0.001814
81                0.007107
82                0.003972
83               -0.001500
84                0.000764

[85 rows x 1 columns]

Octavo día

In [44]:
df

Rendimiento S&P
0           0.006378
1           0.004021
2           0.007009
3           0.001661
4           0.001302
..               ...
591         0.000133
592        -0.020713
593        -0.017617
594         0.011459
595         0.003919

[596 rows x 1 columns]

In [45]:
#8
#Nos quedamos con 592 días
#Se elimina 4 observaciones 
rend8_1 = df['Rendimiento S&P'][4:596:1]
rend8_1 = np.array(rend8_1)
rend8_1

array([ 1.30208347e-03, -1.11284596e-03,  7.00902609e-03,  6.72692617e-03,
       -3.53071313e-03,  9.37100631e-03, -1.61769775e-03,  4.37564815e-03,
        8.03436443e-03,  2.17200493e-03, -5.60132635e-04,  6.02439421e-04,
        1.17716380e-02, -6.75473632e-03, -1.09586426e-02,  4.88865875e-04,
       -6.48298662e-04, -2.14366803e-02, -4.18425412e-02,  1.72905737e-02,
       -5.01413842e-03, -3.82590522e-02,  1.48256453e-02,  1.38186656e-02,
        2.60952183e-03,  1.33134400e-02,  1.19968616e-02,  3.73399822e-04,
       -5.85851713e-03, -5.51166462e-03,  9.73077555e-04,  1.59012783e-02,
        1.16884387e-02, -1.27883117e-02, -1.11578060e-02, -1.34139658e-02,
        5.05878544e-03,  1.09716175e-02,  2.63538301e-03, -4.83991694e-04,
        4.45314825e-03,  1.72295465e-02, -1.27479704e-03, -6.38391044e-03,
       -5.74097014e-03, -7.82236274e-04,  1.70199808e-03, -1.43060406e-02,
        1.48070847e-03, -1.84569184e-03, -2.54848873e-02, -2.11898071e-02,
        2.67950407e-02, -

In [46]:
st.mean([rend8_1[0], rend8_1[1], rend8_1[2], rend8_1[3], rend8_1[4], rend8_1[5], rend8_1[6], rend8_1[7]])

0.002815429168322781

In [47]:
st.mean([rend8_1[584], rend8_1[585], rend8_1[586], rend8_1[587], rend8_1[588], rend8_1[589], rend8_1[590], rend8_1[591]])

-0.00020672868988237387

In [48]:
rend8 = []
for i in range(74):
    rend8.append(st.mean([rend8_1[8*i], rend8_1[(8*i)+1], rend8_1[(8*i)+2], rend8_1[(8*i)+3], rend8_1[(8*i)+4], rend8_1[(8*i)+5], rend8_1[(8*i)+6], rend8_1[(8*i)+7]]))

rend8 = pd.DataFrame({'Medias de Rendimientos': rend8})
rend8

rend8.to_excel('Rend8.xlsx')

In [49]:
rend8

Medias de Rendimientos
0                 0.002815
1                 0.000599
2                -0.007658
3                 0.004225
4                -0.000936
..                     ...
69                0.008774
70                0.008282
71                0.001627
72                0.003117
73               -0.000207

[74 rows x 1 columns]

Noveno día

In [50]:
df

Rendimiento S&P
0           0.006378
1           0.004021
2           0.007009
3           0.001661
4           0.001302
..               ...
591         0.000133
592        -0.020713
593        -0.017617
594         0.011459
595         0.003919

[596 rows x 1 columns]

In [51]:
#9
#Nos quedamos con 594 días
#Se elimina 2 observaciones 
rend9_1 = df['Rendimiento S&P'][2:596:1]
rend9_1 = np.array(rend9_1)
rend9_1

array([ 7.00914585e-03,  1.66096392e-03,  1.30208347e-03, -1.11284596e-03,
        7.00902609e-03,  6.72692617e-03, -3.53071313e-03,  9.37100631e-03,
       -1.61769775e-03,  4.37564815e-03,  8.03436443e-03,  2.17200493e-03,
       -5.60132635e-04,  6.02439421e-04,  1.17716380e-02, -6.75473632e-03,
       -1.09586426e-02,  4.88865875e-04, -6.48298662e-04, -2.14366803e-02,
       -4.18425412e-02,  1.72905737e-02, -5.01413842e-03, -3.82590522e-02,
        1.48256453e-02,  1.38186656e-02,  2.60952183e-03,  1.33134400e-02,
        1.19968616e-02,  3.73399822e-04, -5.85851713e-03, -5.51166462e-03,
        9.73077555e-04,  1.59012783e-02,  1.16884387e-02, -1.27883117e-02,
       -1.11578060e-02, -1.34139658e-02,  5.05878544e-03,  1.09716175e-02,
        2.63538301e-03, -4.83991694e-04,  4.45314825e-03,  1.72295465e-02,
       -1.27479704e-03, -6.38391044e-03, -5.74097014e-03, -7.82236274e-04,
        1.70199808e-03, -1.43060406e-02,  1.48070847e-03, -1.84569184e-03,
       -2.54848873e-02, -

In [52]:
st.mean([rend9_1[0], rend9_1[1], rend9_1[2], rend9_1[3], rend9_1[4], rend9_1[5], rend9_1[6], rend9_1[7], rend9_1[8]])

0.0029797661063334867

In [53]:
st.mean([rend9_1[585], rend9_1[586], rend9_1[587], rend9_1[588], rend9_1[589], rend9_1[590], rend9_1[591], rend9_1[592], rend9_1[593]])

0.0008162339577266966

In [54]:
rend9 = []
for i in range(66):
    rend9.append(st.mean([rend9_1[9*i], rend9_1[(9*i)+1], rend9_1[(9*i)+2], rend9_1[(9*i)+3], rend9_1[(9*i)+4], rend9_1[(9*i)+5], rend9_1[(9*i)+6], rend9_1[(9*i)+7], rend9_1[(9*i)+8]]))

rend9 = pd.DataFrame({'Medias de Rendimientos': rend9})
rend9

rend9.to_excel('Rend9.xlsx')

In [55]:
rend9

Medias de Rendimientos
0                 0.002980
1                 0.001019
2                -0.006517
3                 0.003343
4                 0.001558
..                     ...
61               -0.000228
62                0.007960
63                0.003177
64                0.004230
65                0.000816

[66 rows x 1 columns]

Décimo día

In [56]:
df

Rendimiento S&P
0           0.006378
1           0.004021
2           0.007009
3           0.001661
4           0.001302
..               ...
591         0.000133
592        -0.020713
593        -0.017617
594         0.011459
595         0.003919

[596 rows x 1 columns]

In [57]:
#10
#Nos quedamos con 590 días
#Se elimina 6 observaciones 
rend10_1 = df['Rendimiento S&P'][6:596:1]
rend10_1 = np.array(rend10_1)
rend10_1

array([ 7.00902609e-03,  6.72692617e-03, -3.53071313e-03,  9.37100631e-03,
       -1.61769775e-03,  4.37564815e-03,  8.03436443e-03,  2.17200493e-03,
       -5.60132635e-04,  6.02439421e-04,  1.17716380e-02, -6.75473632e-03,
       -1.09586426e-02,  4.88865875e-04, -6.48298662e-04, -2.14366803e-02,
       -4.18425412e-02,  1.72905737e-02, -5.01413842e-03, -3.82590522e-02,
        1.48256453e-02,  1.38186656e-02,  2.60952183e-03,  1.33134400e-02,
        1.19968616e-02,  3.73399822e-04, -5.85851713e-03, -5.51166462e-03,
        9.73077555e-04,  1.59012783e-02,  1.16884387e-02, -1.27883117e-02,
       -1.11578060e-02, -1.34139658e-02,  5.05878544e-03,  1.09716175e-02,
        2.63538301e-03, -4.83991694e-04,  4.45314825e-03,  1.72295465e-02,
       -1.27479704e-03, -6.38391044e-03, -5.74097014e-03, -7.82236274e-04,
        1.70199808e-03, -1.43060406e-02,  1.48070847e-03, -1.84569184e-03,
       -2.54848873e-02, -2.11898071e-02,  2.67950407e-02, -1.74272858e-02,
       -2.92091883e-03,  

In [58]:
st.mean([rend10_1[0], rend10_1[1], rend10_1[2], rend10_1[3], rend10_1[4], rend10_1[5], rend10_1[6], rend10_1[7], rend10_1[8], rend10_1[9]])

0.0032582871974992694

In [59]:
st.mean([rend10_1[580], rend10_1[581], rend10_1[582], rend10_1[583], rend10_1[584], rend10_1[585], rend10_1[586], rend10_1[587], rend10_1[588], rend10_1[589]])

0.0011586928093863635

In [60]:
rend10 = []
for i in range(59):
    rend10.append(st.mean([rend10_1[10*i], rend10_1[(10*i)+1], rend10_1[(10*i)+2], rend10_1[(10*i)+3], rend10_1[(10*i)+4], rend10_1[(10*i)+5], rend10_1[(10*i)+6], rend10_1[(10*i)+7], rend10_1[(10*i)+8], rend10_1[(10*i)+9]]))

rend10 = pd.DataFrame({'Medias de Rendimientos': rend10})
rend10

rend10.to_excel('Rend10.xlsx')

In [61]:
rend10.head(5)

Medias de Rendimientos
0                0.003258
1               -0.009536
2                0.006244
3                0.001419
4               -0.007383

In [62]:
rend10.tail(5)

Medias de Rendimientos
54               -0.022719
55                0.004762
56                0.012891
57               -0.001537
58                0.001159

Onceavo día

In [63]:
df

Rendimiento S&P
0           0.006378
1           0.004021
2           0.007009
3           0.001661
4           0.001302
..               ...
591         0.000133
592        -0.020713
593        -0.017617
594         0.011459
595         0.003919

[596 rows x 1 columns]

In [64]:
#11
#Nos quedamos con 594 días
#Se elimina 2 observaciones 
rend11_1 = df['Rendimiento S&P'][2:596:1]
rend11_1 = np.array(rend11_1)
rend11_1

array([ 7.00914585e-03,  1.66096392e-03,  1.30208347e-03, -1.11284596e-03,
        7.00902609e-03,  6.72692617e-03, -3.53071313e-03,  9.37100631e-03,
       -1.61769775e-03,  4.37564815e-03,  8.03436443e-03,  2.17200493e-03,
       -5.60132635e-04,  6.02439421e-04,  1.17716380e-02, -6.75473632e-03,
       -1.09586426e-02,  4.88865875e-04, -6.48298662e-04, -2.14366803e-02,
       -4.18425412e-02,  1.72905737e-02, -5.01413842e-03, -3.82590522e-02,
        1.48256453e-02,  1.38186656e-02,  2.60952183e-03,  1.33134400e-02,
        1.19968616e-02,  3.73399822e-04, -5.85851713e-03, -5.51166462e-03,
        9.73077555e-04,  1.59012783e-02,  1.16884387e-02, -1.27883117e-02,
       -1.11578060e-02, -1.34139658e-02,  5.05878544e-03,  1.09716175e-02,
        2.63538301e-03, -4.83991694e-04,  4.45314825e-03,  1.72295465e-02,
       -1.27479704e-03, -6.38391044e-03, -5.74097014e-03, -7.82236274e-04,
        1.70199808e-03, -1.43060406e-02,  1.48070847e-03, -1.84569184e-03,
       -2.54848873e-02, -

In [65]:
st.mean([rend11_1[0], rend11_1[1], rend11_1[2], rend11_1[3], rend11_1[4], rend11_1[5], rend11_1[6], rend11_1[7], rend11_1[8], rend11_1[9], rend11_1[10]])

0.003566173412463553

In [66]:
st.mean([rend11_1[583], rend11_1[584], rend11_1[585], rend11_1[586], rend11_1[587], rend11_1[588], rend11_1[589], rend11_1[590], rend11_1[591], rend11_1[592], rend11_1[593]])

-0.0015339348202024136

In [67]:
rend11 = []
for i in range(54):
    rend11.append(st.mean([rend11_1[11*i], rend11_1[(11*i)+1], rend11_1[(11*i)+2], rend11_1[(11*i)+3], rend11_1[(11*i)+4], rend11_1[(11*i)+5], rend11_1[(11*i)+6], rend11_1[(11*i)+7], rend11_1[(11*i)+8], rend11_1[(11*i)+9], rend11_1[(11*i)+10]]))

rend11 = pd.DataFrame({'Medias de Rendimientos': rend11})
rend11

rend11.to_excel('Rend11.xlsx')

In [68]:
rend11.head(5)

Medias de Rendimientos
0                0.003566
1               -0.004534
2                0.000297
3                0.002736
4               -0.004276

In [69]:
rend11.tail(5)

Medias de Rendimientos
49               -0.008562
50               -0.002874
51                0.005268
52                0.004121
53               -0.001534